/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedQuoteRequestsRouteImport } from './routes/_authenticated/quote-requests'
import { Route as AuthenticatedManufacturingOrdersRouteImport } from './routes/_authenticated/manufacturing-orders'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAiReviewRouteImport } from './routes/_authenticated/ai-review'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as AuthenticatedExportIndexRouteImport } from './routes/_authenticated/export/index'
import { Route as AuthenticatedDuplicatesIndexRouteImport } from './routes/_authenticated/duplicates/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedApiCenterIndexRouteImport } from './routes/_authenticated/api-center/index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products/$id'
import { Route as AuthenticatedAssetsUnlinkedRouteImport } from './routes/_authenticated/assets/unlinked'
import { Route as AuthenticatedAssetsDuplicatesRouteImport } from './routes/_authenticated/assets/duplicates'
import { Route as AuthenticatedAssetsBulkUploadRouteImport } from './routes/_authenticated/assets/bulk-upload'
import { Route as ApiPublicV1SuppliersRouteImport } from './routes/api/public/v1/suppliers'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicV1PricingRouteImport } from './routes/api/public/v1/pricing'
import { Route as ApiPublicV1AssetsRouteImport } from './routes/api/public/v1/assets'
import { Route as ApiAgentV1QuoteResponseRouteImport } from './routes/api/agent/v1/quote-response'
import { Route as ApiAgentV1QuoteRequestRouteImport } from './routes/api/agent/v1/quote-request'
import { Route as ApiAgentV1OrderStatusRouteImport } from './routes/api/agent/v1/order-status'
import { Route as ApiPublicV1ProductsAzCodeRouteImport } from './routes/api/public/v1/products/$azCode'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuoteRequestsRoute =
  AuthenticatedQuoteRequestsRouteImport.update({
    id: '/quote-requests',
    path: '/quote-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManufacturingOrdersRoute =
  AuthenticatedManufacturingOrdersRouteImport.update({
    id: '/manufacturing-orders',
    path: '/manufacturing-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiReviewRoute = AuthenticatedAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportIndexRoute =
  AuthenticatedExportIndexRouteImport.update({
    id: '/export/',
    path: '/export/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDuplicatesIndexRoute =
  AuthenticatedDuplicatesIndexRouteImport.update({
    id: '/duplicates/',
    path: '/duplicates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApiCenterIndexRoute =
  AuthenticatedApiCenterIndexRouteImport.update({
    id: '/api-center/',
    path: '/api-center/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsUnlinkedRoute =
  AuthenticatedAssetsUnlinkedRouteImport.update({
    id: '/assets/unlinked',
    path: '/assets/unlinked',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsDuplicatesRoute =
  AuthenticatedAssetsDuplicatesRouteImport.update({
    id: '/assets/duplicates',
    path: '/assets/duplicates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsBulkUploadRoute =
  AuthenticatedAssetsBulkUploadRouteImport.update({
    id: '/assets/bulk-upload',
    path: '/assets/bulk-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicV1SuppliersRoute = ApiPublicV1SuppliersRouteImport.update({
  id: '/api/public/v1/suppliers',
  path: '/api/public/v1/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PricingRoute = ApiPublicV1PricingRouteImport.update({
  id: '/api/public/v1/pricing',
  path: '/api/public/v1/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AssetsRoute = ApiPublicV1AssetsRouteImport.update({
  id: '/api/public/v1/assets',
  path: '/api/public/v1/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1QuoteResponseRoute = ApiAgentV1QuoteResponseRouteImport.update({
  id: '/api/agent/v1/quote-response',
  path: '/api/agent/v1/quote-response',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1QuoteRequestRoute = ApiAgentV1QuoteRequestRouteImport.update({
  id: '/api/agent/v1/quote-request',
  path: '/api/agent/v1/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentV1OrderStatusRoute = ApiAgentV1OrderStatusRouteImport.update({
  id: '/api/agent/v1/order-status',
  path: '/api/agent/v1/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsAzCodeRoute =
  ApiPublicV1ProductsAzCodeRouteImport.update({
    id: '/$azCode',
    path: '/$azCode',
    getParentRoute: () => ApiPublicV1ProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/manufacturing-orders': typeof AuthenticatedManufacturingOrdersRoute
  '/quote-requests': typeof AuthenticatedQuoteRequestsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/api-center/': typeof AuthenticatedApiCenterIndexRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/duplicates/': typeof AuthenticatedDuplicatesIndexRoute
  '/export/': typeof AuthenticatedExportIndexRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/api/agent/v1/order-status': typeof ApiAgentV1OrderStatusRoute
  '/api/agent/v1/quote-request': typeof ApiAgentV1QuoteRequestRoute
  '/api/agent/v1/quote-response': typeof ApiAgentV1QuoteResponseRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/suppliers': typeof ApiPublicV1SuppliersRoute
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/manufacturing-orders': typeof AuthenticatedManufacturingOrdersRoute
  '/quote-requests': typeof AuthenticatedQuoteRequestsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/api-center': typeof AuthenticatedApiCenterIndexRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/duplicates': typeof AuthenticatedDuplicatesIndexRoute
  '/export': typeof AuthenticatedExportIndexRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/api/agent/v1/order-status': typeof ApiAgentV1OrderStatusRoute
  '/api/agent/v1/quote-request': typeof ApiAgentV1QuoteRequestRoute
  '/api/agent/v1/quote-response': typeof ApiAgentV1QuoteResponseRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/suppliers': typeof ApiPublicV1SuppliersRoute
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ai-review': typeof AuthenticatedAiReviewRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/manufacturing-orders': typeof AuthenticatedManufacturingOrdersRoute
  '/_authenticated/quote-requests': typeof AuthenticatedQuoteRequestsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/_authenticated/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/_authenticated/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/api-center/': typeof AuthenticatedApiCenterIndexRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/duplicates/': typeof AuthenticatedDuplicatesIndexRoute
  '/_authenticated/export/': typeof AuthenticatedExportIndexRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/api/agent/v1/order-status': typeof ApiAgentV1OrderStatusRoute
  '/api/agent/v1/quote-request': typeof ApiAgentV1QuoteRequestRoute
  '/api/agent/v1/quote-response': typeof ApiAgentV1QuoteResponseRoute
  '/api/public/v1/assets': typeof ApiPublicV1AssetsRoute
  '/api/public/v1/pricing': typeof ApiPublicV1PricingRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/suppliers': typeof ApiPublicV1SuppliersRoute
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-review'
    | '/audit-logs'
    | '/dashboard'
    | '/integrations'
    | '/manufacturing-orders'
    | '/quote-requests'
    | '/support'
    | '/assets/bulk-upload'
    | '/assets/duplicates'
    | '/assets/unlinked'
    | '/products/$id'
    | '/api-center/'
    | '/assets/'
    | '/duplicates/'
    | '/export/'
    | '/import/'
    | '/pricing/'
    | '/products/'
    | '/requests/'
    | '/settings/'
    | '/suppliers/'
    | '/api/agent/v1/order-status'
    | '/api/agent/v1/quote-request'
    | '/api/agent/v1/quote-response'
    | '/api/public/v1/assets'
    | '/api/public/v1/pricing'
    | '/api/public/v1/products'
    | '/api/public/v1/suppliers'
    | '/api/public/v1/products/$azCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-review'
    | '/audit-logs'
    | '/dashboard'
    | '/integrations'
    | '/manufacturing-orders'
    | '/quote-requests'
    | '/support'
    | '/assets/bulk-upload'
    | '/assets/duplicates'
    | '/assets/unlinked'
    | '/products/$id'
    | '/api-center'
    | '/assets'
    | '/duplicates'
    | '/export'
    | '/import'
    | '/pricing'
    | '/products'
    | '/requests'
    | '/settings'
    | '/suppliers'
    | '/api/agent/v1/order-status'
    | '/api/agent/v1/quote-request'
    | '/api/agent/v1/quote-response'
    | '/api/public/v1/assets'
    | '/api/public/v1/pricing'
    | '/api/public/v1/products'
    | '/api/public/v1/suppliers'
    | '/api/public/v1/products/$azCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ai-review'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/manufacturing-orders'
    | '/_authenticated/quote-requests'
    | '/_authenticated/support'
    | '/_authenticated/assets/bulk-upload'
    | '/_authenticated/assets/duplicates'
    | '/_authenticated/assets/unlinked'
    | '/_authenticated/products/$id'
    | '/_authenticated/api-center/'
    | '/_authenticated/assets/'
    | '/_authenticated/duplicates/'
    | '/_authenticated/export/'
    | '/_authenticated/import/'
    | '/_authenticated/pricing/'
    | '/_authenticated/products/'
    | '/_authenticated/requests/'
    | '/_authenticated/settings/'
    | '/_authenticated/suppliers/'
    | '/api/agent/v1/order-status'
    | '/api/agent/v1/quote-request'
    | '/api/agent/v1/quote-response'
    | '/api/public/v1/assets'
    | '/api/public/v1/pricing'
    | '/api/public/v1/products'
    | '/api/public/v1/suppliers'
    | '/api/public/v1/products/$azCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAgentV1OrderStatusRoute: typeof ApiAgentV1OrderStatusRoute
  ApiAgentV1QuoteRequestRoute: typeof ApiAgentV1QuoteRequestRoute
  ApiAgentV1QuoteResponseRoute: typeof ApiAgentV1QuoteResponseRoute
  ApiPublicV1AssetsRoute: typeof ApiPublicV1AssetsRoute
  ApiPublicV1PricingRoute: typeof ApiPublicV1PricingRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRouteWithChildren
  ApiPublicV1SuppliersRoute: typeof ApiPublicV1SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quote-requests': {
      id: '/_authenticated/quote-requests'
      path: '/quote-requests'
      fullPath: '/quote-requests'
      preLoaderRoute: typeof AuthenticatedQuoteRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturing-orders': {
      id: '/_authenticated/manufacturing-orders'
      path: '/manufacturing-orders'
      fullPath: '/manufacturing-orders'
      preLoaderRoute: typeof AuthenticatedManufacturingOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-review': {
      id: '/_authenticated/ai-review'
      path: '/ai-review'
      fullPath: '/ai-review'
      preLoaderRoute: typeof AuthenticatedAiReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export/': {
      id: '/_authenticated/export/'
      path: '/export'
      fullPath: '/export/'
      preLoaderRoute: typeof AuthenticatedExportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/duplicates/': {
      id: '/_authenticated/duplicates/'
      path: '/duplicates'
      fullPath: '/duplicates/'
      preLoaderRoute: typeof AuthenticatedDuplicatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-center/': {
      id: '/_authenticated/api-center/'
      path: '/api-center'
      fullPath: '/api-center/'
      preLoaderRoute: typeof AuthenticatedApiCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/unlinked': {
      id: '/_authenticated/assets/unlinked'
      path: '/assets/unlinked'
      fullPath: '/assets/unlinked'
      preLoaderRoute: typeof AuthenticatedAssetsUnlinkedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/duplicates': {
      id: '/_authenticated/assets/duplicates'
      path: '/assets/duplicates'
      fullPath: '/assets/duplicates'
      preLoaderRoute: typeof AuthenticatedAssetsDuplicatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/bulk-upload': {
      id: '/_authenticated/assets/bulk-upload'
      path: '/assets/bulk-upload'
      fullPath: '/assets/bulk-upload'
      preLoaderRoute: typeof AuthenticatedAssetsBulkUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/suppliers': {
      id: '/api/public/v1/suppliers'
      path: '/api/public/v1/suppliers'
      fullPath: '/api/public/v1/suppliers'
      preLoaderRoute: typeof ApiPublicV1SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/pricing': {
      id: '/api/public/v1/pricing'
      path: '/api/public/v1/pricing'
      fullPath: '/api/public/v1/pricing'
      preLoaderRoute: typeof ApiPublicV1PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/assets': {
      id: '/api/public/v1/assets'
      path: '/api/public/v1/assets'
      fullPath: '/api/public/v1/assets'
      preLoaderRoute: typeof ApiPublicV1AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/quote-response': {
      id: '/api/agent/v1/quote-response'
      path: '/api/agent/v1/quote-response'
      fullPath: '/api/agent/v1/quote-response'
      preLoaderRoute: typeof ApiAgentV1QuoteResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/quote-request': {
      id: '/api/agent/v1/quote-request'
      path: '/api/agent/v1/quote-request'
      fullPath: '/api/agent/v1/quote-request'
      preLoaderRoute: typeof ApiAgentV1QuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/v1/order-status': {
      id: '/api/agent/v1/order-status'
      path: '/api/agent/v1/order-status'
      fullPath: '/api/agent/v1/order-status'
      preLoaderRoute: typeof ApiAgentV1OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$azCode': {
      id: '/api/public/v1/products/$azCode'
      path: '/$azCode'
      fullPath: '/api/public/v1/products/$azCode'
      preLoaderRoute: typeof ApiPublicV1ProductsAzCodeRouteImport
      parentRoute: typeof ApiPublicV1ProductsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiReviewRoute: typeof AuthenticatedAiReviewRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedManufacturingOrdersRoute: typeof AuthenticatedManufacturingOrdersRoute
  AuthenticatedQuoteRequestsRoute: typeof AuthenticatedQuoteRequestsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAssetsBulkUploadRoute: typeof AuthenticatedAssetsBulkUploadRoute
  AuthenticatedAssetsDuplicatesRoute: typeof AuthenticatedAssetsDuplicatesRoute
  AuthenticatedAssetsUnlinkedRoute: typeof AuthenticatedAssetsUnlinkedRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedApiCenterIndexRoute: typeof AuthenticatedApiCenterIndexRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedDuplicatesIndexRoute: typeof AuthenticatedDuplicatesIndexRoute
  AuthenticatedExportIndexRoute: typeof AuthenticatedExportIndexRoute
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiReviewRoute: AuthenticatedAiReviewRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedManufacturingOrdersRoute: AuthenticatedManufacturingOrdersRoute,
  AuthenticatedQuoteRequestsRoute: AuthenticatedQuoteRequestsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAssetsBulkUploadRoute: AuthenticatedAssetsBulkUploadRoute,
  AuthenticatedAssetsDuplicatesRoute: AuthenticatedAssetsDuplicatesRoute,
  AuthenticatedAssetsUnlinkedRoute: AuthenticatedAssetsUnlinkedRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedApiCenterIndexRoute: AuthenticatedApiCenterIndexRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedDuplicatesIndexRoute: AuthenticatedDuplicatesIndexRoute,
  AuthenticatedExportIndexRoute: AuthenticatedExportIndexRoute,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1ProductsRouteChildren {
  ApiPublicV1ProductsAzCodeRoute: typeof ApiPublicV1ProductsAzCodeRoute
}

const ApiPublicV1ProductsRouteChildren: ApiPublicV1ProductsRouteChildren = {
  ApiPublicV1ProductsAzCodeRoute: ApiPublicV1ProductsAzCodeRoute,
}

const ApiPublicV1ProductsRouteWithChildren =
  ApiPublicV1ProductsRoute._addFileChildren(ApiPublicV1ProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAgentV1OrderStatusRoute: ApiAgentV1OrderStatusRoute,
  ApiAgentV1QuoteRequestRoute: ApiAgentV1QuoteRequestRoute,
  ApiAgentV1QuoteResponseRoute: ApiAgentV1QuoteResponseRoute,
  ApiPublicV1AssetsRoute: ApiPublicV1AssetsRoute,
  ApiPublicV1PricingRoute: ApiPublicV1PricingRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRouteWithChildren,
  ApiPublicV1SuppliersRoute: ApiPublicV1SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
