/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets/index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products/$id'
import { Route as AuthenticatedAssetsUnlinkedRouteImport } from './routes/_authenticated/assets/unlinked'
import { Route as AuthenticatedAssetsDuplicatesRouteImport } from './routes/_authenticated/assets/duplicates'
import { Route as AuthenticatedAssetsBulkUploadRouteImport } from './routes/_authenticated/assets/bulk-upload'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicV1ProductsAzCodeRouteImport } from './routes/api/public/v1/products/$azCode'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsUnlinkedRoute =
  AuthenticatedAssetsUnlinkedRouteImport.update({
    id: '/assets/unlinked',
    path: '/assets/unlinked',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsDuplicatesRoute =
  AuthenticatedAssetsDuplicatesRouteImport.update({
    id: '/assets/duplicates',
    path: '/assets/duplicates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsBulkUploadRoute =
  AuthenticatedAssetsBulkUploadRouteImport.update({
    id: '/assets/bulk-upload',
    path: '/assets/bulk-upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsAzCodeRoute =
  ApiPublicV1ProductsAzCodeRouteImport.update({
    id: '/$azCode',
    path: '/$azCode',
    getParentRoute: () => ApiPublicV1ProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/support': typeof AuthenticatedSupportRoute
  '/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/support': typeof AuthenticatedSupportRoute
  '/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/assets/bulk-upload': typeof AuthenticatedAssetsBulkUploadRoute
  '/_authenticated/assets/duplicates': typeof AuthenticatedAssetsDuplicatesRoute
  '/_authenticated/assets/unlinked': typeof AuthenticatedAssetsUnlinkedRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$azCode': typeof ApiPublicV1ProductsAzCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/support'
    | '/assets/bulk-upload'
    | '/assets/duplicates'
    | '/assets/unlinked'
    | '/products/$id'
    | '/assets/'
    | '/pricing/'
    | '/products/'
    | '/suppliers/'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$azCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/support'
    | '/assets/bulk-upload'
    | '/assets/duplicates'
    | '/assets/unlinked'
    | '/products/$id'
    | '/assets'
    | '/pricing'
    | '/products'
    | '/suppliers'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$azCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/support'
    | '/_authenticated/assets/bulk-upload'
    | '/_authenticated/assets/duplicates'
    | '/_authenticated/assets/unlinked'
    | '/_authenticated/products/$id'
    | '/_authenticated/assets/'
    | '/_authenticated/pricing/'
    | '/_authenticated/products/'
    | '/_authenticated/suppliers/'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$azCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/unlinked': {
      id: '/_authenticated/assets/unlinked'
      path: '/assets/unlinked'
      fullPath: '/assets/unlinked'
      preLoaderRoute: typeof AuthenticatedAssetsUnlinkedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/duplicates': {
      id: '/_authenticated/assets/duplicates'
      path: '/assets/duplicates'
      fullPath: '/assets/duplicates'
      preLoaderRoute: typeof AuthenticatedAssetsDuplicatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets/bulk-upload': {
      id: '/_authenticated/assets/bulk-upload'
      path: '/assets/bulk-upload'
      fullPath: '/assets/bulk-upload'
      preLoaderRoute: typeof AuthenticatedAssetsBulkUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$azCode': {
      id: '/api/public/v1/products/$azCode'
      path: '/$azCode'
      fullPath: '/api/public/v1/products/$azCode'
      preLoaderRoute: typeof ApiPublicV1ProductsAzCodeRouteImport
      parentRoute: typeof ApiPublicV1ProductsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAssetsBulkUploadRoute: typeof AuthenticatedAssetsBulkUploadRoute
  AuthenticatedAssetsDuplicatesRoute: typeof AuthenticatedAssetsDuplicatesRoute
  AuthenticatedAssetsUnlinkedRoute: typeof AuthenticatedAssetsUnlinkedRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAssetsBulkUploadRoute: AuthenticatedAssetsBulkUploadRoute,
  AuthenticatedAssetsDuplicatesRoute: AuthenticatedAssetsDuplicatesRoute,
  AuthenticatedAssetsUnlinkedRoute: AuthenticatedAssetsUnlinkedRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1ProductsRouteChildren {
  ApiPublicV1ProductsAzCodeRoute: typeof ApiPublicV1ProductsAzCodeRoute
}

const ApiPublicV1ProductsRouteChildren: ApiPublicV1ProductsRouteChildren = {
  ApiPublicV1ProductsAzCodeRoute: ApiPublicV1ProductsAzCodeRoute,
}

const ApiPublicV1ProductsRouteWithChildren =
  ApiPublicV1ProductsRoute._addFileChildren(ApiPublicV1ProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
